### ISSUE TITLE
Task list for first test release

### ISSUE THREAD

**Issue by soc** [ogc-schemas/ogc-schemas#3]
For Java:
  - [x] Make sure Java build works: Maven 3 requires a newer Java than 6, but 8 works and should be fine?
  - [x] Sort out publishing on Maven Central #1

For JavaScript:
  - [x] Make sure JavaScript build works
  - [x] Sort out publishing on NPM
